language: python
matrix:
  include:
    - { python: "2.7" }
    - { python: "3.4" }
    - { python: "3.5" }
    - { python: "3.6" }
    - { python: "3.7" }
    - { python: "3.8" }
    - { python: "3.9" }
    - { python: "pypy" }
    - { python: "pypy3" }
    - { python: "nightly" }
  allow_failures:
    - python: "nightly"
script:
  - "python setup.py test"
deploy:
  provider: pypi
  user: edgewall-org
  password:
    secure: "W86OIU/V9PbXdERXbR1vTOw/GvxoNyn5gt7n52TGqjI1BcklX1t31uPgBnf0wmlp/kY9vMbOYhuqUWpBhbMKMBY6zOuNnCV0H5vynZ/nWefSBK6Fqyl2zTsdLYfzUKAIPBldYcaiJMZ6eD++ujVsgWN6XglP7jYogqjJFxxNf6s="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
